exclude: >
  (?x)^(
    bzl/version.tpl.cc|
    bzl/version.tpl.py|
    ci/pipeline.yml|
    plaidbench/plaidbench/networks/keras/imdb_lstm.h5|
    pmlc/target/x86/heatmap_skx_xeonplat_8180_1-7GHz_mblocked.csv.gz
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
  - repo: local
    hooks:
      - id: buildifier
        name: buildifier
        entry: buildifier
        language: system
        files: (^BUILD|\.BUILD|\.bzl|^WORKSPACE)$
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx|js|proto)$
        args: ["-i"]
      - id: cpplint
        name: cpplint
        entry: cpplint
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        args:
          - --filter=-legal/copyright,-readability/todo,-build/c++11
          - --linelength=120
      - id: nbstripout
        name: nbstripout
        entry: nbstripout
        language: python
        files: '\.ipynb$'
      - id: yapf
        name: yapf
        entry: yapf
        language: system
        files: \.py$
        args: [-i]
