exclude: >
  (?x)^(
    base/util/catch.h|
    bzl/version.tpl.cc|
    bzl/conda.tpl.py|
    vendor/opengl/inc/.*
  )$
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
  - repo: local
    hooks:
      - id: buildifier
        name: buildifier
        entry: buildifier
        language: system
        files: (^BUILD|\.BUILD|\.bzl|^WORKSPACE)$
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx|js|proto)$
        args: ["-i"]
      - id: cpplint
        name: cpplint
        entry: cpplint
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        args:
          - --filter=-legal/copyright,-readability/todo,-build/c++11
          - --linelength=120
      - id: yapf
        name: yapf
        entry: yapf
        language: system
        files: \.py$
        args: [-i]
