channels:
  - conda-forge
dependencies:
  - blas=2.113
  - boost=1.76.0
  - ccache=4.1
  - cffi=1.14.4
  - cmake=3.13.4
  - cython=0.29.22
  - doxygen=1.9.1
  - git=2.32.0
  - libusb=1.0.25
  - matplotlib=3.4.1
  - ninja=1.10.2
  - numpy=1.18.5
  - opencv=4.5.2
  - pip=21.0.1
  - pre_commit=2.11.1
  - python=3.7
  - pystache=0.5.4
  - pyyaml=5.4.1
  - yapf=0.27
  - pip:
      - asq==1.3
      - breathe==4.28.0
      - clang-format==9.0.0
      - click==7.1.2
      - cpplint==1.4.4
      - keras==2.2.4
      - keras-applications==1.0.8
      - livereload==2.6.3
      - nbstripout==0.3.9
      - opencv-python-headless==4.5.3.56
      - pcpp==1.20.1
      - sphinx-rtd-theme==0.5.1
      - sphinxcontrib-katex==0.7.1
      - sphinxcontrib-napoleon==0.7
      - sphinx-tabs==1.3.0
      - tensorflow==1.15.5
      - theano==1.0.5
