# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PlaidML
description: >-
  A platform for making deep learning work everywhere.
baseurl: /plaidml/
url: https://plaidml.github.io

# Build settings
markdown: kramdown
#markdown: maruku
kramdown:
  math_engine: katex
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# just-the-docs settings
logo: /assets/images/plaid-final.png

# Enable or disable the site search
# Supports true (default) or false
# search_enabled: true

# Enable support for hyphenated search words:
# search_tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
# aux_links:
#   "Just the Docs on GitHub":
#     - "//github.com/pmarsceill/just-the-docs"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false/nil
# heading_anchors: true

# Footer content appears at the bottom of every page's main content
# footer_content: "Copyright &copy; 2017-2019 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Color scheme currently only supports "dark" or nil (default)
#color_scheme: "dark"

# Google Analytics Tracking (optional)
#ga_tracking: UA-5555555-55
